### ISSUE TITLE
FDSC: Duplicate feedback

### ISSUE THREAD

**Issue by Cerbrus** [Charcoal-SE/userscripts#36]
See [this metasmoke report.](https://metasmoke.erwaysoftware.com/post/57414)

Apparently, Mithrandir managed to send tpu- feedback from FDSC, twice. Both checkmarks on the report say:

> Mithrandir (From FDSC): tpu-

Mithrandir [doesn't recall](http://chat.stackexchange.com/transcript/message/35453651#35453651) sending duplicate feedback.

**Comment by ArtOfCode-** [comment]
gremlins

**Comment by ArtOfCode-** [comment]
Realistically, there's not much I can do to troubleshoot this. This is the first time I've heard of it happening in over 24000 feedbacks from FDSC. So, thanks for bringing it up - I'm going to close this for now because there's nowt I can do, but if it happens again/becomes a recurring thing, please reopen this.

**Comment by Fortunate-MAN** [comment]
@ArtOfCode- this just happened again: http://chat.stackexchange.com/transcript/message/35518683#35518683

[MS](https://metasmoke.erwaysoftware.com/post/57767) shows that Undo feedbacked through FDSC twice. 

As a side note, the "tpu- by Undo" did not appear in chat even though it was the first feedback and I had feedbacked it after Undo's feedback.

**Comment by Undo1** [comment]
I know. It happens.

**Comment by angussidney** [comment]
I'm closing this for now, since there haven't been any issues in over 6 months now. Additionally, MS now properly handles duplicate feedback (through overwriting), and most people are using FIRE, so this is probably no longer relevant.
