### ISSUE TITLE
Add a linter and CI

### ISSUE THREAD

**Issue by j-f1** [Charcoal-SE/userscripts#37]
We should add a linter to manage code style. Personally, I’m in favor of [standard](http://standardjs.com), but another style would be fine. We should:

- [ ] add a Travis script that runs tests on all of the `*.user.js` files
- [ ] add a way to install the linter locally and test before commiting

**Comment by angussidney** [comment]
I know it's a good idea to have CI for most projects, but because these userscripts are so small and all have different code styling, is this really worth it?

**Comment by ArtOfCode-** [comment]
I'd be in favour of having something to enforce code style. Otherwise, worst-case, we end up with a bunch of userscripts by different people with wildly varying code styles, which makes maintenance harder.

**Comment by j-f1** [comment]
Which style?

* 😄 For [standard](http://standardjs.com)
* 🎉  For [JSHint](http://jshint.com)

(add as reaction)
<sup>Feel free to suggest more</sup>

**Comment by ArtOfCode-** [comment]
Bah, definitely not standard if it doesn't enforce semicolons. That's an *excellent* way to introduce bugs.

**Comment by j-f1** [comment]
@ArtIfCode- Why does it introduce bugs?

**Comment by ArtOfCode-** [comment]
@j-f1 On its own, it doesn't, but it's a hazard similar to inline `if` statements. This is a bug risk:

    if (condition)
        doThing();

because it's formatted exactly the same as a regular `if`. If the next programmer comes along to add something to that and isn't 100% focused, it's too easy to miss the lack of braces and add a statement to what you *think* is the if block but is actually outside. That's difficult to track down.

In the same *sort of* way, not having semicolon-terminated lines is a risk for scope bugs: you think you're adding a new call, but in reality the parser reads and executes it as a continuation of the last line. Again, that's difficult to track down.

Languages like Python and Ruby are fine for this because they were *designed* for it, and have strictly defined characteristics for what terminates a line and what doesn't. JS was designed originally with semicolons, then no-semicolons was shoehorned in because it would be cool. Line termination characteristics without semicolons are loosely defined, so it's much easier to make mistakes.

**Comment by j-f1** [comment]
@ArtOfCode- JavaScript has rules regarding semicolon insertion that all modern browsers follow. Quoted from Standard:

> * No semicolons – [It's](http://blog.izs.me/post/2353458699/an-open-letter-to-javascript-leaders-regarding) [fine.](http://inimino.org/~inimino/blog/javascript_semicolons) [Really!](https://www.youtube.com/watch?v=gsfbh17Ax9I)
> * Never start a line with (, [, or `
>    * This is the **only** gotcha with omitting semicolons – *automatically checked for you!*
>    * [More details](http://standardjs.com/rules.html#semicolons)

Also, lots of people use it: [npm](https://github.com/npm/npm/blob/892f531130d38dfd40000794dc9087b483bb1ee9/package.json#L218), [Electron](https://github.com/electron/electron/blob/1f75df0253c7cee435f2783029ed26ea20ea7ad0/package.json#L36), and [lots more](https://raw.githubusercontent.com/feross/standard-packages/master/all.json).

**Comment by honnza** [comment]
Not omitting semicolons is the standard practice and I'd rather see it
kept. It's easier for the brain than having to think about a list of
characters I can't use.

( is often found at the start of a line if you use an immediately invoked
function expression, (function(){...})().
[ can start an array literal - and it's not unusual for me to iterate over
a constant array.
` is probably not to be worried about, I guess...

Also, add + to the list. You can still use ~ and ! as the ways (both
non-standard) to invoke function expressions, though.

**Comment by honnza** [comment]
The izs blog suggests putting semicolons on the offending lines, but that's
pretty ugly in my opinion.

Also, the way it presents rule #4 is mildly incorrect. + and - can be used
as unary operators, and yet when they start a line, ASI prefers not to put
a semicolon before them, unlike what the wording suggests is the case.

Then he "gets opinionated and pisses everyone off" (by the author's own
wording).

**Comment by Glorfindel83** [comment]
Please enforce the use of semicolons. I don't care if the browser automatically inserts them or not; my brain doesn't. It's like SMS language; having less rules makes a message *harder* to parse, not easier.

**Comment by j-f1** [comment]
Since everyone is in favor of JSHint, I’ll be adding that as a test script. Who should manage the Travis CI integration?

**Comment by ArtOfCode-** [comment]
I believe anyone who has repo access can set up Travis. @j-f1 probably knows most about what needs setting up?

**Comment by ArtOfCode-** [comment]
(side-note: for local testing, [Atom](https://atom.io) has a plugin for JSHint that will automatically test your code as you go)

**Comment by j-f1** [comment]
@ArtOfCode- Travis says:

> Sorry, but we can't find any repositories you have admin access to.
> You require admin rights to enable these repositories
