### ISSUE TITLE
Show all reasons in Smokey reports

### ISSUE THREAD

**Issue by j-f1** [Charcoal-SE/userscripts#65]
Currently, Smokey only posts a limited set of reasons because chat messages have length limits. AIM could edit the DOM of these messages after-the-fact, showing all reasons, even if the message would then go over the length limit.

**Comment by Cerbrus** [comment]
If the list of reasons is that long, do we really need to see'm all in the chat message?

Especially since FIRE now shows these reasons when you hover over the "question:" above the reported post's body:

![untitled](https://cloud.githubusercontent.com/assets/2911988/24048127/376c06b2-0b28-11e7-9f7a-b2ae44ac9e7a.png)

**Comment by angussidney** [comment]
I assume AIM already has access to this info, so this sounds like a good way to implement it. +1

**Comment by Cerbrus** [comment]
I've worked out a small change that adds this.

However, it's depends on [this MS api bug](https://github.com/Charcoal-SE/metasmoke/issues/143) getting fixed.
